### ISSUE TITLE
Does not fire element change events

### ISSUE THREAD

**Issue by fidian** [akahuku/wasavi#100]
If you go to http://prettyprinter.org/ you will see this problem more clearly.  When using ":wq" this doesn't fire the element's change event so Angular doesn't pick up the new value of the element.

If I follow the instructions as shown on http://stackoverflow.com/questions/2856513/how-can-i-trigger-an-onchange-event-manually, the page updates correctly.

    evt = document.createEvent("HTMLEvents");
    evt.initEvent("change", false, true);
    $('textarea').dispatchEvent(evt);

I am using Chrome on Linux.

**Comment by akahuku** [comment]
It is a good idea that fire `input` and `change` event after wasavi updates the content of element.
Thank you.
