### ISSUE TITLE
Install procedure with Firefox

### ISSUE THREAD

**Issue by quicknir** [akahuku/wasavi#106]
There's no link for the Firefox version of the plugin, and wasavi doesn't appear on the official Firefox addon page. How should I go about installing this on Firefox?

**Comment by akahuku** [comment]
I gave up submitting wasavi to [AMO](https://addons.mozilla.org/en-US/firefox/) because their review process is VERY slow.
Please use [develop version](https://github.com/akahuku/wasavi/raw/master/dist/wasavi.xpi).

**Comment by Nefari0uss** [comment]
@akahuku Would you reconsider uploading the addon to AMO now? There should be a faster process now for addons to get approved.

**Comment by flxai** [comment]
Is this plugin still working for current Firefox releases? If so I'd like to support submitting to AMO.

**Comment by sheldonth** [comment]
Any updates on possible firefox support?
