### ISSUE TITLE
Don't strip newlines in contenteditable (workflowy)

### ISSUE THREAD

**Issue by adamschmideg** [akahuku/wasavi#117]
I use wasavi with [workflowy](http://www.workflowy.com).  When I edit a note (which is in a contenteditable div), then move away from the note to another node, all newlines are removed in the content of the note.  I need the newlines to be kept as they are.  I use Chrome 47.0.2526.111.

**Comment by akahuku** [comment]
Confirmed. Thank you.

**Comment by adamschmideg** [comment]
I installed it from github and it works, thank you.  Once you upload it to the chrome store, it'll be available from wasavi v0.6.616
