### ISSUE TITLE
gk (or k with :set jkdenotative) not working

### ISSUE THREAD

**Issue by PhilRunninger** [akahuku/wasavi#119]
I just got an update to wasavi (version 0.6.606), and I noticed that I can no longer go up to the previous line using the `gk` keystroke. I get the same behavior when I `:set jkdenotative` and use the `k` keystroke.

**Comment by akahuku** [comment]
Confirmed. thank you.

**Comment by PhilRunninger** [comment]
Closing this, because it has been fixed for a long time now.
