### ISSUE TITLE
Feature Request: Open wasavi text-area in full-screen

### ISSUE THREAD

**Issue by k0pernikus** [akahuku/wasavi#121]
I really would like to type in fullscreen mode. I like having a zen-modish do-not-disturb-me-while-typing mode, so it would be awesome for wasavi to be able to open in fullscreen mode.

Currently, it only fits to the current textarea content width and height.

Or as a meta-picture (look at all the wasted whitespace!):

![Look at the whitespace!](https://cloud.githubusercontent.com/assets/436935/13494831/15682070-e147-11e5-9d57-f6d90007c8f6.png)

Hence I kindly request that wasavi supports a open in fullscreen mode.

**Comment by akahuku** [comment]
Thank you for using wasavi.
wasavi has fullscreen functionality: `:set fullscreen` or `:set nofullscreen`.
This makes wasavi maximize and restore in the client area of a browser.

Or, do you want the 'true' fullscreen functionality?

**Comment by k0pernikus** [comment]
@akahuku h`:set fullscreen` is pretty sufficient. Thanks for pointing it out.

Is there a way to make toggling it easier? As a nice to have feature, I would like the option to set that fullscreen as default for any page. As currently it seems it is only stored per window/textarea.

**Comment by akahuku** [comment]
In the same way as vim/vi, wasavi executes sequence of ex commands when it starts.
Enter `:options` to open preference page, and edit 'exrc' textbox.
For example, put `:set fullscreen` into exrc, wasavi would always start in the maximized state.

**Comment by broomdodger** [comment]
`map` a keystroke
When in wasavi, type "`:opt`" at the command line,
then in the wasavi options window
enter the following:
```
map ,ff :set fullscreen!<enter>
```
or any unused key combo
Note: the "!" performs the toggle
