### ISSUE TITLE
Does not work with Google Inbox

### ISSUE THREAD

**Issue by thaldyron** [akahuku/wasavi#122]

**Comment by cam5** [comment]
Me too! There was no issue with Google Inbox as recently as last week for me. I'm using Chrome 48.0.2564.116 on Mac OS X El Capitan.

**Comment by akahuku** [comment]
@thaldyron 
What is your browser?
I tried to make new mail at https://inbox.google.com/ on Chrome, wasavi started.

**Comment by thaldyron** [comment]
Updated to latest Chrome; issue resolved for me.

**Comment by cam5** [comment]
+1 I'm on 49.0.2623.87, now, and wasavi works again in inbox.google.com for me. :smile:
