### ISSUE TITLE
[Feature request] Visual Line Navigation

### ISSUE THREAD

**Issue by agzam** [akahuku/wasavi#138]
Is it possible to have a setting option that would toggle "Visual Line Navigation" rather than logical line navigation. Basically when it's "on" it would you use `gj` and `gk` instead of `j` and `k`

**Comment by rglassett** [comment]
@agzam: Isn't this already implemented? Try `:set jkdemarcative`

**Comment by agzam** [comment]
oh ok. did not know that. The setting is `set jkdenotative`. Thanks!
