### ISSUE TITLE
[Firefox] Wasavi painfully slow with e10s

### ISSUE THREAD

**Issue by Timvde** [akahuku/wasavi#144]
When using in an e10s (multi-process) enabled Firefox build, Wasavi slows down the entire browser to a crawl. This is probably due to excessive usage of CPOWs.

More information on https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox and https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts

**Comment by akahuku** [comment]
Thank you.
The latest wasavi is based on the WebExtensions technology.
So, there should be no interprocess communication by CPOW.

**Comment by Timvde** [comment]
Doesn't seem to work :( Although it's not your fault.

From the browser console:

`wasavi backend: ERROR: TypeError: chrome.identity.onSignInChanged is undefined`

Which is not supported yet according to [Are We WebExtensions Yet?](http://arewewebextensionsyet.com/). A quick search on Bugzilla pointed me to [bug 1320862](https://bugzilla.mozilla.org/show_bug.cgi?id=1320862).

Going from the Wasavi code, it seems like this has something to do with sync. Is there an easy way to disable it? I don't need (nor want) to sync anything.

**Comment by Timvde** [comment]
Thanks, it's a step closer to working in Firefox! Now the issue is that [`chrome.tabs.sendRequest`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Tabs/sendRequest) is undefined. It is marked as deprecated and replaced by [`sendMessage`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/sendMessage). Mozilla has decided not to implement any deprecated APIs.

I would try this myself, since the change seems trivial, but I didn't manage to build the add-on. I installed npm, ran `npm install` (which ended with errors, it said it could not run `distribute-scripts`), then ran `distribute-scripts` myself (no output here at all), and finally `make xpi`. Do you have build instructions somewhere? It is my first time ever I try to build an add-on myself, so sorry if I did something stupid :)

**Comment by Timvde** [comment]
Looks like we're still a way off. Firefox *also* doesn't support [`clipboardRead`](https://bugzilla.mozilla.org/show_bug.cgi?id=1312260) yet.

**Comment by akahuku** [comment]
I added the document about build and test wasavi:
https://github.com/akahuku/wasavi/blob/master/BUILD-AND-TEST.md

It is not mandatory to build xpi to develop wasavi. Install web-ext with npm, and
```
$ make debug-firefox
```
The command launches Firefox for debugging with built-in wasavi.

**Comment by Timvde** [comment]
I just tested the latest unstable release, and it works great on Nightly! Thanks :)
