### ISSUE TITLE
Wasavi does not stay over the textarea when resizing the window

### ISSUE THREAD

**Issue by Larivact** [akahuku/wasavi#169]
Instead it floats where the textarea was before. This is quite annoying since it discourages resizing the browser window when using wasavi.

**Comment by akahuku** [comment]
Tell me the URL where the problem occurs and your browser.

**Comment by Larivact** [comment]
github.com both comment and gist text areas, Firefox 54.0.1

**Comment by akahuku** [comment]
Thank you, confirmed.

**Comment by Larivact** [comment]
Still happens when the browser window is narrower than the text area.
