### ISSUE TITLE
Mappings in visual mode

### ISSUE THREAD

**Issue by HaleTom** [akahuku/wasavi#173]
I'd like to make mappings for cut / copy when text is selected in visual mode, eg:

```
vmap <C-C> "*y
vmap <C-X> "*d
```

Is there a way to do this?

**Comment by akahuku** [comment]
Although not a `vmap`, I implemented equivalent feature.
Please see [document](https://github.com/akahuku/wasavi/wiki/Syntax-of-Map-command).

**Comment by HaleTom** [comment]
Thanks!

For others wondering, [bound mode](https://github.com/akahuku/wasavi#bound-mode-commands) mappings are kinda like vim's `vmap`.

**Comment by HaleTom** [comment]
I came up with the following for the clipboard:

```
" Copy
map [bound] <C-C> "*y
" Cut
map [bound] <C-X> "*d
" Paste, overwriting selection:
map [bound] <C-V> x"*P
```
