### ISSUE TITLE
Compatibility with multi process Firefox 54 & up?

### ISSUE THREAD

**Issue by stianeklund** [akahuku/wasavi#175]
Any way Wasavi can become compatible for multi threading which is in Firefox builds 54 & up?

**Comment by jasontibbitts** [comment]
I've been running firefox nightly and as far as I can tell, wasavi has no issues with multiprocess.  It's not marked as either legacy or multiprocess incompatible in the addons screen.  What leads you to believe that there's an issue?

**Comment by stianeklund** [comment]
@jasontibbitts Interesting, for me with Wasavi 0.6.641 & Firefox 54.0 it says it's not compatible with multi-processes.

**Comment by jasontibbitts** [comment]
I'm using 0.6.690, which I installed by clicking on the file in the 'dist' directory here on github.  Even 0.6.641 is older than what's in the github 'Releases' tab.

**Comment by stianeklund** [comment]
@jasontibbitts Ah ok, then in that case this isn't an issue as soon as the new build hits the Firefox "Add-On's".

**Comment by jasontibbitts** [comment]
Note that build isn't "new"; I believe it was made on March 12.
