### ISSUE TITLE
Input sometimes double counted

### ISSUE THREAD

**Issue by nocylah** [akahuku/wasavi#176]
Keyboard input is sometimes double-counted, seemingly when I type too fast. I've encountered this bug in all modes. I'm using wasavi 0.7.711 in Firefox 54.0.1 on Linux, with the VimFX plugin also installed.
![example](https://user-images.githubusercontent.com/1113394/28187910-7aa2f6c2-67dd-11e7-96e1-9a7e6857edf2.gif)

**Comment by ybhvf** [comment]
This bug appears to be fixed now :).
