### ISSUE TITLE
Text doesn't output correctly in Slack

### ISSUE THREAD

**Issue by zefreak** [akahuku/wasavi#177]
When creating a slack comment, I can open wasavi but when I save and quit, only a newline is inserted in the text area. I haven't seen this issue on other sites yet.

**Comment by zgana** [comment]
I can confirm that behavior in Slack is fixed with
```
set writeas='{ \
  "http://*.slack.com/*": "p", \
}'
```
in my Wasavi exrc.

**Comment by zefreak** [comment]
Excellent, thank you for the help
