### ISSUE TITLE
Map commands do not get stored

### ISSUE THREAD

**Issue by devout-coder** [akahuku/wasavi#228]
I have set a few keybindings using map command...But when i close wasavi vim and reopen it again I am not able to use these key bindings..How can I make sure than key bindings persist across multiple sessions?

**Comment by moustario** [comment]
For anyone with the same issue, there is a vimrc-like config in the extension settings.
![image](https://user-images.githubusercontent.com/45439249/167591090-905d8d94-dfbf-4c8d-a13b-adb2d592bd90.png)
![image](https://user-images.githubusercontent.com/45439249/167592084-53f4b234-3d74-4659-879a-d2918ee5fc6d.png)
This is also mentioned in the doc [here](https://github.com/akahuku/wasavi#how-to-modify-initial-settings).

**Comment by devout-coder** [comment]
That was really helpful, thank you so much!
