### ISSUE TITLE
Prevent closing the tab if unsaved

### ISSUE THREAD

**Issue by dimator** [akahuku/wasavi#30]
Hi,

I've lost work a couple of times because I accidentally hit ctrl-w (to delete previous word) only to close the chrome tab :(

maybe something with window.onbeforeunload ? Either that or intercept the ctrl-w key combo?

Thanks!

**Comment by MaMrEzO** [comment]
I'm using the [Better Ctrl-w](https://chrome.google.com/webstore/detail/better-ctrl-w/jfknaapblnppeflfamkegnnonlfgokhp) plugin in Chrome, which instead of the other same plugins lets you set a new shortcut to close the tab.
