### ISSUE TITLE
online gmail blank lines removed

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#31]
acer c720 chromebook
wasavi 0.6.246

Is there a setting that is causing blank lines to be removed from online gmail when editing an existing email?

Blank lines are NOT removed posting this issue at wasavi.

Good news...
Using wasavi with online gmail seems to work with 'COMPOSE', that is create a new email.
Previously wasavi only would work when replying to online gmail.

**Comment by PrestanceDesign** [comment]
Hi,

With the last version, il happen again. I opened this issue #134 about that.

**Comment by PrestanceDesign** [comment]
I capture the HTML of my message both before and after editing/saving with wasavi. Maybe this can help to debug.

### Before :
``` html
<div id=":93" class="Am aO9 Al editable LW-avf" hidefocus="true" aria-label="Corps du message" g_editable="true" role="textbox" contenteditable="true" tabindex="1" style="direction: ltr; min-height: 85px;">This is the first line.<div><br></div><div>This is the second line.</div></div>
```

### After :
``` html
<div id=":93" class="Am aO9 Al editable LW-avf" hidefocus="true" aria-label="Corps du message" g_editable="true" role="textbox" contenteditable="true" tabindex="1" style="direction: ltr; min-height: 85px;"><div>This is the first line.</div>
<div>This is the second line.</div>
</div>
```

**Comment by bitterjug** [comment]
i'm experiencing this problem today with 0.6.675
