### ISSUE TITLE
vim `i_CTRL-O`

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#57]
Will `<c-o>` be implemented?
vim `:help i_CTRL-O`
CTRL-O  execute one command, return to Insert mode

**Comment by akahuku** [comment]
Umm... `<c-o>` has lot of notice and trap as you can read the help.
Also in implement, perhaps several distorted tricks will be needed.
That is to say, nesting a normal mode and an input mode, I don't think that's such a great idea...

**Comment by broomdodger** [comment]
Thank you for your comment.
I do not now remember why I asked.
And... wasavi works GREAT without the complication.
