### ISSUE TITLE
`j` and `k` are slow

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#58]
acer c720 chromebook
chrome 38.0.2125.108
wasavi 0.6.340

normal mode: `j` and `k` are slow but `<enter>` and `-` are fast

Tapping `j` multiple times quickly, cursor will disappear or hang for some time then move.
Tapping `<enter>` multiple times quickly the cursor moves immediately.

`11 j` to move down is slow, but `11 <enter>` is fast.

**Comment by broomdodger** [comment]
acer c720 chromebook
chrome 40.0.2214.115
wasavi 0.6.368

Still the same slow `j` and `k`

**Comment by akahuku** [comment]
Ah, are not you `:set jkdenotative` in your exrc?

**Comment by broomdodger** [comment]
Yes I had `:set jkdenotative` in the exrc.
I changed to `:set nojkdenotative` and jk are working fast.

**Comment by akahuku** [comment]
Ok I got what is the bottleneck. Thank you.

**Comment by broomdodger** [comment]
wasavi 0.6.372 has fixed j and k movement.
With `:set jkdenotative` jk are now **fast**
and move within the text correctly.
