### ISSUE TITLE
<CR> not recognized in a map

### ISSUE THREAD

**Issue by bohrshaw** [akahuku/wasavi#61]
With `map ZQ :q!<CR>`, `ZQ` is actually mapped to `:q!`, without the `<CR>`.

**Comment by nesmyslny** [comment]
@bohrshaw: try using `<enter>` instead of `<CR>`. This works for me: `map <Space>w :w<enter>`
Hope this helps :)

**Comment by bohrshaw** [comment]
Thanks. @nesmyslny
