### ISSUE TITLE
Doesn't work on gmail.

### ISSUE THREAD

**Issue by VdeVatman** [akahuku/wasavi#65]
there are a group of textareas where wasavi just doesn't work, like here or gmail, and I guess almost every hard customized textarea. Is there any fix for this?

**Comment by kerray** [comment]
Also doesn't work on Google Docs - which would be incredible.

**Comment by broomdodger** [comment]
acer c720 chromebook
chrome 40.0.2214.115
wasavi 0.6.368

For me... seems to work in gmail and in this textarea.

**Comment by VdeVatman** [comment]
I'm not using wasavi anymore, at the end I found 'control+i' vimperator's shortcut for launching a background vim proccess the best solution.

**Comment by broomdodger** [comment]
Would you mind closing this issue?
