### ISSUE TITLE
Any chance to import vim plugins?

### ISSUE THREAD

**Issue by VdeVatman** [akahuku/wasavi#66]
Is there a way (or is it planed?) for importing vim plugins into wasavi?

**Comment by akahuku** [comment]
Unfortunately, no.
To import vim plugins, re-implementation of full-spec vimscript engine is needed.
Then, It will take 10 or more seconds to launch wasavi by pressing ctrl+enter!

**Comment by VdeVatman** [comment]
Ok, thanks.
