### ISSUE TITLE
wasavi 0.6.363 `vapy` acting strange

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#67]
acer c720 chromebook
wasavi 0.6.363 `vapy` acting very strange.
If I `vapy` to select several lines, each with a return,
then `P` paste, the result is acting as one line.
A second `P` paste fails.
Sometimes using the arrow keys, or j and k, the cursor disappears.
Sometimes wasavi becomes un-responsive, or hangs.
Tried in gmail and a website text area with the same result.

**Comment by akahuku** [comment]
`vapy` and `P` bug were fixed by 915da4aca0b5f8b20f13b17a43f8df6845bd3a51,

**Comment by broomdodger** [comment]
Several tests and the `vapy` then `P` now seems work.
Thank you.
The screen can be very slow trying to catch up to the `j` and `k` key presses.
`-` and `return` do not seem to have the slow movement.
