### ISSUE TITLE
Soft Word Wrap to Window

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#70]
> acer c720 chromebook
> chromeos 41.0.2272.76 40.0.2214.115
> wasavi 0.6.378

### Soft Word Wrap to Window

When `tw=0` and lines are long,
wasavi wraps lines at the window edge,
but it is NOT wrapping at word boundaries,
it is breaking within words.

Is my wasavi mis-configured?
\--or-- Is this a bug?
\--or-- Is this by design?

**Comment by akahuku** [comment]
At the moment, it is designed behavior.
But I'm planning a bit large change of input mode logic, so word-wrapping will work at that timing.

**Comment by broomdodger** [comment]
chromeos 41.0.2272.89
wasavi 0.6.387

Soft word wrap to window is working.
