### ISSUE TITLE
When is the `exrc` read?

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#71]
>acer c720 chromebook
>chromeos 41.0.2272.89
>wasavi 0.6.387

Under what circumstances is the `exrc` read?

If I use the wasavi command line to `set tw=64`
but have `set tw=0` in the `exrc`
even after **restart** of chromeos the command line option takes precedence

Is it possible read the `exrc` when wasavi is invoked?

**Comment by broomdodger** [comment]
PS
It seems the command line options are associated with specific text boxes or specific gmail emails.

**Comment by akahuku** [comment]
Sorry I have not write a document about setting override.

* List of modified options is stored in extension's persistent storage in the form of array of `:set` command.
* "modified" means "different from its default value that defined in source code".
* Every time wasavi starts, exec is executed.
* Immediately after exrc execution, setting override is also executed. 
* Setting override is independent every URL (max 30 URLs)

**Comment by broomdodger** [comment]
Thank you, that explains what I saw.
Is it possible to reset ALL the override to the `exrc`?

**Comment by akahuku** [comment]
New mechanism is needed.
I think it is better that `:set textwidth&` resets to default value, as same as vim.
and some extensions:

* `:set textwidth&` resets to default value
* `:set textwidth&default` reset to default (formal syntax of `:set textwidth&` )
* `:set textwidth&exrc` resets to the value at the timing that executed exrc
* `:set all&` resets all options

**Comment by broomdodger** [comment]
I never want the `Setting override is independent every URL (max 30 URLs)`
I **always** want my `exrc` to replace any previous local changes (as vim does).
Is it possible to have a setting to ignore all previous override?
Such that if I `:set tw=64` it is **temporary** to a specific instance.
Something like adding `:set all&` to the top of the `exrc`?

**Comment by akahuku** [comment]
So, I propose `override` new option.
If you put `:set nooverride` in your exrc, overriding will be skipped.

**Comment by broomdodger** [comment]
Yes... that would be perfect.
Simple and succinct.
I added it to my exrc, commented of course.
Thank you.

**Comment by broomdodger** [comment]
> To return a setting to default state:
> :set <option-name>&
> :set <option-name>&default
> :set all&
> :set all&default

Do these 2 do the same?
```
:set <option-name>&
:set <option-name>&default
```

Do these 2 do the same?
```
:set all&
:set all&default
```

**Comment by akahuku** [comment]
Yes, specifying only "&" is a shortcut of "&default" and those processes are completely same.

**Comment by broomdodger** [comment]
Thank you for the clarification.
