### ISSUE TITLE
Does not launch when replying to message in 'Outlook WebApp'

### ISSUE THREAD

**Issue by ma-ti** [akahuku/wasavi#72]
Hi,
when I try to reply to a message in 'Outlook WebApp' I use at work I cannot launch the wasavi.
Similarlly, sometimes wasavi does not launch when I try to edit an already filled 'Subject' line.
Writing new message works fine, and it works too on the other websites I use regularly.
System: Firefox 36.0.1 with wasavi 0.6.387, NoScript, AdBlock and others on Windows 7.

Otherwise, thanks for the great add-on!

Best,
martin

**Comment by Lupus** [comment]
OWA uses an Iframe. Try to compose plaintext email and it will work fine.

I already filed an issue about editing an iframe document, but the answer was to disable html formatting by the means of web interface and use wasavi afterwards.

**Comment by ma-ti** [comment]
@Lupus: Thanks for the explanation.
