### ISSUE TITLE
unix style timestamp

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#76]
Would you consider an option for the date stamp to use a unix style timestamp?
example: `strftime("%Y%m%d.%H%M%S") = 20150402.224312`
```
'Y' four digit year (2015)
'm' month number leading zero (01-12)
'd' day number leading zero (01-31)
'H' hour leading zero 24h format (00-23)
'M' minute leading zero (00-59)
'S' second leading zero (00-59)
```

**Comment by akahuku** [comment]
Where that be used in wasavi?

**Comment by broomdodger** [comment]
I would like to insert date_time into text that I am editing.

Currently I am using this map to insert the wasavi date_time into text:
`map! ,dd <esc>"DPa<space>`

The map inserts date_time in this format:
`5/23/2015, 10:33:42 AM `

I would prefer date.time in this format:
`20150523.103342`

In unix time format would be:
`%Y%m%d.%H%M%S`

So I would like this date.time format anywhere that wasavi date_time ("D") would be used:
Does this answer your question?

**Comment by akahuku** [comment]
Thank you, a new option to specify the date time format would be necessary.

P.S. To read register contents in input mode, you just need only to press `^R` `D`.

**Comment by broomdodger** [comment]
This morning wasavi reported it was updated to 0.6.420 and strftime was added.
Thank you!
How do set strftime? so that register D will return the new date.time.

**Comment by akahuku** [comment]
for example, `:set datetime=%Y%m%d.%H%M%S`

**Comment by broomdodger** [comment]
Thank you, now I can time stamp everything :)

BEFORE I posted the question I tried:
`set datetime=strftime("%Y%m%d.%H%M%S")`
`set datetime=strftime('%Y%m%d.%H%M%S')`

AFTER I posted the question I tried:
`set datetime="%Y%m%d.%H%M%S"`
`set datetime='%Y%m%d.%H%M%S'`

and then:
`set datetime=%Y%m%d.%H%M%S`
and it worked. `20150526.080111`

This works:
`set datetime=%A-%d-%B-%Y`
Tuesday-26-May-2015

How would I make spaces in the date like?
Tuesday 26 May 2015

**Comment by broomdodger** [comment]
I tried escaping space, did not work.
`set datetime=%A\ %d\ %B\ %Y`

I tried quoting, did not work.
`set datetime=%A" "%d" "%B" "%Y`
`set datetime=%A' '%d' '%B' '%Y`

**Comment by akahuku** [comment]
Ah, this is one of the strange spec of vi, to escape a space you have to put `^V` in front of space character.
`^V` will be entered when you press `Ctrl+V` twice...

**Comment by broomdodger** [comment]
That works for the wasavi command line.

But how to add it to the wasavi options exrc?
`^v` is paste there.

In vim another way to escape is to use `\`

**Comment by akahuku** [comment]
Oh I misunderstood.
posix defines that escape character in the set command is backslash.

**Comment by broomdodger** [comment]
Thank you...

`set datetime=%A\ %Y\ %B\ %d\ at\ %H:%M\ test\ 1\ %%`
now correctly produces this:
`Sunday 2015 May 31 at 06:42 test 1 %`

And **even better**, this works:
`set datetime='%A %Y %B %d at %H:%M test 2 %%'`
to produce this:
`Sunday 2015 May 31 at 06:45 test 2 %`
