### ISSUE TITLE
[Feature request] Context menu item to launch wasavi

### ISSUE THREAD

**Issue by talha131** [akahuku/wasavi#8]
The keybinding `Ctrl`+`Enter` does not work in all text areas. For example, if I press this keyboard shortcut in Github issue tracker, it submits/updates the issue instead of launching wasavi on Firefox.

For such cases, it will be great to have a context menu item to launch wasavi.

**Comment by brianjmurrell** [comment]
The context menu doesn't seem to work in GitHub PR/Issue comment boxes.  Should it?
