### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'setEndAfter' on 'Range': The node provided is null.

### ISSUE THREAD

**Issue by mzcarlos** [akahuku/wasavi#80]
Hello!

I'm Using Google Chrome 42.0.2311.90.

In insert mode, When I type dead_acute key, then type another key (e.g. "a" in order to get "á"),  it hangs and I get the following error. It works fine in Firefox 31.6.0.

Uncaught NotFoundError: Failed to execute 'setEndAfter' on 'Range': The node provided is null.
divideLine	@	classes.js:2465
(anonymous function)	@	wasavi.js:3611
update	@	classes.js:1590
(anonymous function)	@	wasavi.js:3610
$call	@	utils.js:66
insert	@	wasavi.js:3583
editMap.
	@	wasavi.js:7165
editMap.	@	wasavi.js:7157
execMap	@	wasavi.js:2407
execEditMap	@	wasavi.js:1869
modeHandlers.edit	@	wasavi.js:5059
processInput	@	wasavi.js:1892
run	@	classes.js:1066
process	@	classes.js:1144
handleKeydown	@	wasavi.js:4312
fire	@	qeema.js:475
sweep	@	qeema.js:1413
pushCompositionedString	@	qeema.js:619
CompositionResult.run	@	qeema.js:154
inputWebkit	@	qeema.js:1046

**Comment by akahuku** [comment]
Confirmed on chrome, thank you.
I'll fix the bug.
