### ISSUE TITLE
wasavi and ChromeOS Auto-correction

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#83]
>acer c720 chromebook
>wasavi 0.6.432
>ChromeOS 43.0.2357.81
>+ Settings
>+ Languages and input
>+ US Keyboard
>+ Configure...
>+ Auto-correction
>+ either **Modest** or **Aggressive**

This is the first time I tried `Auto-correction` with wasavi.

Use wasavi to type a line of text, tap enter at the end of a line,
a second copy of the last word of the line will be added.
Also typing a word spelled wrong will have strange results.

None of this happens with `Auto-correction` Off

**Comment by akahuku** [comment]
That feature seems like be enabled on ChromeOS only.
When google also made the function enable to Chrome for PCs, I may be able to debug.

**Comment by broomdodger** [comment]
acer c720 chromebook
ChromeOS 44.0.2403.155
wasavi 0.6.545

Today I set `Auto-correction` to `ON` and it is working with wasavi.
Either the ChromeOS update or wasavi has FIXED the problem.
