### ISSUE TITLE
Theme Request

### ISSUE THREAD

**Issue by biell** [akahuku/wasavi#84]
Can you add the following theme into "src/chrome/frontend/classes_ui.js" at line 98?  If you like,
I can send a diff.  Feel free to change the theme name.  Awesome extension, by the way.  Thanks.

          },
          matrix: {   
               statusHue:'#2ba',
               background:'#050505',
               overTextMarkerFg:'#2ba',
               warnedStatusFg:'#fff', warnedStatusBg:'#e30',
               invertFg:'#000', invertBg:'#1e4',  
               blurFg:'#0f0', blurBg:'#050505',
               
               rowBgOdd:'#0a0a0a',
               editCursorFg:'#2ba', 
               statusFg:'#000',
               lineNumberFg:'#2ba', lineNumberBg:'#080808',
               rowFg:'#0f0', rowBg:'#050505',
               highlightFg:'highlight', highlightBg:'highlighttext',
               lineInputFg:'#0f0', lineInputBg:'rgba(0,0,0,0.9)',       
               consoleFg:'#0f0', consoleBg:'#111',
               boundFg:'#0f0', boundBg:'#011'
          }

**Comment by akahuku** [comment]
Thank you!
By the way, by anything but a pull request, your name is not recorded in commit log.
Don't you mind with that?

**Comment by biell** [comment]
Thank you, I don't need credit in the commit log.  My favorite color scheme is thanks enough.

Thank you for such a wonderful plugin.   It makes the gmail web interface not competely horrible.

**Comment by klaernie** [comment]
@akahuku : as you committed this and it works (looks quite nice!) you should close this issue.

**Comment by biell** [comment]
Theme works, thank you.
