### ISSUE TITLE
add substitute [a]ll to :s

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#85]
> acer c720 chromebook
> ChromeOS 43.0.2357.81
> wasavi 0.6.457

Can you add a replace **all** to `:s`?
Currently wasavi has:
`Substitute? ([y]es, [n]o, [q]uit)`

I often start a substitute with [c]onfirm as:
`:.,$s/^/> /c`
and after seeing it work correctly I would like to replace the remaining.

I find it easier to read **without** the parens:
`Substitute? [y]es, [n]o, [a]ll, [q]uit`

**Comment by akahuku** [comment]
I have been thinking of that request will come sometime.
I'm implementing [a]ll and [l]ast now.

**Comment by broomdodger** [comment]
Thank you.
`:s` is now working very well.
Substitutions with or without the `g` option also work properly.
