### ISSUE TITLE
:wq and submit form

### ISSUE THREAD

**Issue by klaernie** [akahuku/wasavi#87]
Hi there,

loving the extension, makes life much nicer. But I noticed over time, that many multi-field forms on the web have the multiline textboxes near the end. So I have grown the habit of editing this last, as this is also, where wasavi shines most.

So would it be possible `:wq` a wasavi session and submit the form this textbox belongs to?

Regards, Andre

**Comment by akahuku** [comment]
Thank you so much for your suggestion.

Since the `:wq` is quite basic, to impart auto-submit function to the command will make many sites convenient, and will make some sites inconvenient.

Therefore I think it's better to create the new command, like `:wqs` (write-quit-submit) -- how about this?

**Comment by klaernie** [comment]
Thats exactly what I was thinking - never break existing vi/vim behavior. I was rather thinking of `:submit` that implies a `:wq`. But either way is fine.

On July 21, 2015 9:41:38 AM GMT+02:00, akahuku <notifications@github.com> wrote:
>Thank you so much for your suggestion.
>
>Since the `:wq` is quite basic, to impart auto-submit function to the
>command will make many sites convenient, and will make some sites
>inconvenient.
>
>Therefore I think it's better to create the new command, like `:wqs`
>(write-quit-submit) -- how about this?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/akahuku/wasavi/issues/87#issuecomment-123201051

-- 
Andre Klärner

Telefon: 0351/79666546
Fax:	 0351/79688547
Mobil:   0172/9838653

Anschrift:
Prohliser Allee 43
01239 Dresden

**Comment by akahuku** [comment]
OK I will implement `:wqs` and `:submit` both (`:submit` is an alias of `:wqs`). Thank you.

**Comment by klaernie** [comment]
I finally had time to test it - works like a treat!
