### ISSUE TITLE
update page load error

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#88]
After recent updates... this page fails to load:

http://dev.appsweets.net/wasavi/

giving this error:

```
This webpage is not available
ERR_NAME_NOT_RESOLVED
```

**Comment by broomdodger** [comment]
wasavi 0.6.513

When trying the online wasavi
http://wasavi.appsweets.net/
a message shows in the middle of the screen
`Press ^C to interrupt.`
Pressing ^C only beeps and I cannot enter insert mode.
Using wasavi in a textarea works good.

**Comment by broomdodger** [comment]
On Linux and ChromeOS
Periodically I get this error from: `http://appsweets.net/wasavi/`

Fatal error: Uncaught exception 'Exception' with message 'Encryption failure' in /virtual/akahuku/public_html/m/crypto.php:133 Stack trace: #0 /virtual/akahuku/public_html/wasavi/index.php(349): SaferCrypto::decrypt('W6F0vD/F0WKZXag...', '???????????????...', true) #1 /virtual/akahuku/public_html/wasavi/index.php(367): initialize() #2 {main} thrown in /virtual/akahuku/public_html/m/crypto.php on line 133

**Comment by akahuku** [comment]
Thank you, fixed the error on <http://appswets.net/wasavi/>.
On the other hand, is there reproducibility of the error on <http://wasavi.appsweets.net/>?

**Comment by broomdodger** [comment]
>On the other hand, is there reproducibility of the error on http://wasavi.appsweets.net/?

**Everytime** I go to that page and wait 5-10 seconds the message:
`Press ^C to interrupt.`
is displayed on Linux Firefox or Linux Chromium or ChromeOS.
I can never start the **online** wasavi editor.

**Comment by akahuku** [comment]
`Press ^C to interrupt` message means that waiting for completion of ex command.
So it may be that the bug depends on your exrc.
Would you tell me your exrc?

**Comment by broomdodger** [comment]
Thank you for the reminder to **debug** the exrc.
I found that **`set nofullscreen`** is causing the `Press ^C to interrupt.`
I commented that line and the online wasavi again works.
I have not changed the exrc in many months
and there is no problem editing a textarea.
```
" exrc
set nooverride
set nosmooth "scroll
" set nofullscreen
set nojkdenotative
set nostripe
```

**Comment by broomdodger** [comment]
If I use the online wasavi editor and type **`:se nofs`**
the screen turns dark grey and soon the `Press ^C to interrupt.` is displayed.

**Comment by broomdodger** [comment]
Thank you.
The online wasavi editor is working with **`:se nofs`**

**Comment by broomdodger** [comment]
**`set nofullscreen`** causes Linux Firefox to display **`Press ^C to interrupt.`**

There is **NO** problem with Linux Chromium or ChromeOS on a Chromebook.
