### ISSUE TITLE
Support number and relativenumber simultaneously

### ISSUE THREAD

**Issue by csssuf** [akahuku/wasavi#91]
In vim, setting nu and rnu together shows the absolute line number for the line under the cursor and the relative line numbers for all other lines. Wasavi currently only supports having one set at a time.

**Comment by broomdodger** [comment]
Thank you @csssuf for suggesting and @akahuku for implementing.
Short test is working and `set number relativenumber` is now in my `exrc`.

**Comment by csssuf** [comment]
@akahuku
