### ISSUE TITLE
Has the list option been implemented

### ISSUE THREAD

**Issue by broomdodger** [akahuku/wasavi#94]
I see **`list`** in **`set all`** but it seems to have no effect.
Has the **`list`** option been implemented?
```
'list'  boolean (default off)
        local to window
List mode: Show tabs as CTRL-I is displayed, display $ after end of
line.  Useful to see the difference between tabs and spaces and for
trailing blanks.
```
If implemented, how to make it display those characters?
What characters should I expect to see?

**Comment by akahuku** [comment]
`list` option exists, but has no effect yet.
I think complex displaying is probably related to syntax highlighting.
