### ISSUE TITLE
Exclude certain fields from using wasavi

### ISSUE THREAD

**Issue by TreyBlancher** [akahuku/wasavi#96]
I use SalesForce on a daily basis at work, in Chrome on OSX.  Everything works great, but
there's a feature called Chatter which posting fields have a lot of Javascript embedded
in it.  One feature is I can type @ and some user or group name, and I'll get a popup
list allowing me to select the item I want.  This will put something like @[John Doe] in
the text.  Unfortunately if I write @[John Doe] in wasavi, SalesForce doesn't recognize
it as a linked user when I post the Chatter comment.

The source of the page allows me to see the name of this input field.  If I could exclude
the input field by name, similar to the way whole URLs are excluded, that would be very
nice.  I don't want to exclude all of SalesForce for me, but certain fields are just
trouble.

**Comment by akahuku** [comment]
In wasavi's options page, there is a blacklist to prevent wasavi from activation per url.
Would you like to control an activation of wasavi per element of page?
So I have an idea which extends the blacklist syntax:
```
[url] ( [space]+ [css selector expression] )?
```
Specifically for example:
```
http://example.net/    *[name="some-name"]
```
This line will prevent wasavi from activation for an element which the name is "some-name" on "http://example.net".  Of course, any elements would also be able to be chosen according to the contents of a selector.
How about this?

**Comment by TreyBlancher** [comment]
That sounds good!  I can inspect the HTML and determine the name of the control
which should be blacklisted.

**Comment by TreyBlancher** [comment]
This works for the main field I tried it on, thank you very much!  When I get my finances
in order I will throw some coin your way.

Thanks again for a great extension, you have NO IDEA how many eons I've been wanting
something like this.

**Comment by a-tanikd** [comment]
hoge

`class`

hoge
